### MATH2504 S2, 2022, BigHW Submission 
### Submission form II of IV 

Student #1 name: Limao Chang

Student #1 ID: 46978554

Student #2 name: Tiarne Graves

Student #2 ID: 46973081

GitHub repo: https://github.com/LimaoC/Limao-Chang__Tiarne-Graves-2504-2022-BigHW

---

**Note: It is expected that this notebook be runnable in the sense that the marker can select "Restart & Run All" and all code cells of solutions will execute. This requires not to have name clashes between solutions.**

---

# Solution to [Question 5](https://courses.smp.uq.edu.au/MATH2504/2022/assessment_html/bighw.html#q5)

In [1]:
"""
Returns the divisors of n in a set.
"""
function get_divisors(n::Int)
    divisors = Set{Int}([1])  # 1 is always a divisor
    # for each pair of divisors (excluding n itself), the lower divisor will always be ≤ √n
    for i in 2:ceil(sqrt(n))
        if n % i == 0
            push!(divisors, i)
            push!(divisors, n ÷ i)
        end
    end
    return divisors
end

"""
Returns whether n is a perfect number (equal to sum of its positive divisors, excluding n).
"""
function is_perfect_number(n::Int)
    return n == sum(get_divisors(n))
end

"""
Prints all the perfect numbers up to limit.
"""
function print_perfect_numbers(limit::Int=1000000)
    for num in 1:limit
        is_perfect_number(num) && println(num)
    end
end

print_perfect_numbers()

1
6
28
496
8128


# Solution to [Question 6](https://courses.smp.uq.edu.au/MATH2504/2022/assessment_html/bighw.html#q6)

In [2]:
"""
Returns a vector of all the primes up to n.
"""
function sieve_of_Eratosthenes(n::Int64)::Vector{Int64}
    primebits::Vector{Bool} = ones(Bool,n) #Will contain true if the index is prime (initially all assumed prime)
    primebits[1] = false #The number 1 is not prime
    p = 2 #Smallest prime
    while p ≤ n
        i = 2p
        while i ≤ n  # \le +[TAB]
            primebits[i] = false
            i += p
        end
        p += 1
        while p ≤ n && !primebits[p]
            p += 1
        end
    end
    (1:n)[primebits]
end

"""
Returns the number of Goldbach pairs each even number in the range [4, n] has.
The ith element corresponds to the even number 2(i+1).
"""
function get_Goldbach_pairs(n::Int64)
    @assert iseven(n)
    @inbounds begin
    # vector of all primes up to n
    primes::Vector{Int64} = sieve_of_Eratosthenes(n)
    # vector of the number of Goldbach pairs each even number in the range [4, n] has
    num_Goldbach_pairs::Vector{Int64} = zeros(length(4:2:n))
    # for each pair, the first (smaller) prime must be <= n÷2. this is the maximum possible index any first prime can reside in.
    max_first_prime_index = last(searchsorted(primes, n÷2))

    # (2, 2) is the only Goldbach pair containing 2, since 2 + p is odd where p is any prime except for 2. so we manually insert
    # it here and ignore 2 everywhere else
    num_Goldbach_pairs[1] = 1

    # for each possible first prime (starting from 3), iterate through all the primes greater than or equal to it (second_prime)
    # and use the sum as the index of the element in the num_Goldbach_pairs to increment.
    # 2 cases:
    # - when first_prime = second_prime, we have first_prime + second_prime = 2first_prime which corresponds to the index
    #   first_prime-1 in the num_Goldbach_pairs vector
    # - when second_prime > first_prime, we first make sure the sum is in range (<= n). this pair is counted twice since the primes
    # are distinct, so we increment by 2 instead (second_prime > first_prime so we don't double up in counts). this corresponds to
    # the index (first_prime+second_prime)÷2-1
    for (first_index, first_prime) in enumerate(primes[2:max_first_prime_index])
        num_Goldbach_pairs[first_prime-1] += 1
        for second_prime in primes[first_index+2:end]  # (first_index+1)+1 to account for enumerate offset (started from 2nd element)
            sum = first_prime + second_prime
            if sum > n  # (first_prime, second_prime) pair is now out of range so we're done for this first_prime
                break
            end
            num_Goldbach_pairs[sum÷2-1] += 2
        end
    end
    end
    return num_Goldbach_pairs
end

using Random, Plots, StatsBase
Random.seed!(0)
n = 10^6
checks = @time get_Goldbach_pairs(n);
even_range_subset = sample(collect(4:2:n), 18000, replace=false);
scatter(even_range_subset, checks[(even_range_subset.÷2).-1], legend=false, xlabel="n", ylabel="Number of Goldpach pairs")

  2.897012 seconds (83.08 k allocations: 17.878 GiB, 6.81% gc time)


# Solution to [Question 7](https://courses.smp.uq.edu.au/MATH2504/2022/assessment_html/bighw.html#q7)

#### 7a:

The function random_license_plate() = String(rand('0':'9',3)) * " " * String(rand('A':'Z',3)), is used to generate a license plate number by creating a random string of 3 numbers from 0-9 with the String(rand('0':'9',3)), and a random string of 3 letters from A-Z with String(rand('A':'Z',3)). These two strings are then combined using * " " * to form a complete number plate. An example of these steps can be seen below:

In [ ]:
s1 = String(rand('0':'9',3))
s2 = String(rand('A':'Z',3))
random_license_plate() = String(rand('0':'9',3)) * " " * String(rand('A':'Z',3))

@show s1
@show s2
@show random_license_plate()

Two strings can be joint together using *, this is utilised to form the number plates by joining strings of letters and numbers together and is depicted below:

In [ ]:
s1 = String(rand('0':'9',3))
s2 = String(rand('A':'Z',3))

@show s1
@show s2
@show s1*s2

rand() is used in multplie places to generate random parts of the strings and number plates. the function rand(), takes vaules to specify what values it can choose from, as well as a value to specify how many values to choose. In rand('A':'Z',3), 'A':Z' indicates the range digits can be selected from. And 3 indicates the number of digits to be selected."

In [ ]:
rand('A':'Z',3)


 [for _ in ] is used to repeat a part of the code for a certain number of times, specified by the range entered ofter 'in'. The _ is left blank as the function it is in reference too does not take a variable, other than number or reptitions.

In [ ]:
N=5
[random_license_plate() for _ in 1:N]

The return value of a function can use a tuple. This is when two desired outputs can be listed next to the same reutrn function by seperating them with a comma resulting in both outputs being presented.

In [ ]:
function counting(N)
    sum = N+2
    multiple = N*2
    
    return sum, multiple
end

counting(3)

sortperm() is a function that takes a vector and then gives an ordered/sorted output of the indexes that vector. sortperm() can be sorted in multiple ways by utilising different commands similar to the sort function. 

In [ ]:
v = [4,7,2]
sortperm(v)
v = [4,7,2];
sortperm(v)
@show sortperm(v)

v2 = [v[3],v[1],v[2]]

#### 7b:

In [ ]:
using BenchmarkTools

function find_special_plate(indexes, plates; special_index = 1234567890)
    for (i, index) in enumerate(indexes) 
        if index == special_index 
            return plates[i]
        end
    end 
    throw(Error("Index not found"))
end

indexes, plates = prepare_sorted_data()

@btime find_special_plate(indexes, plates)

BencmarkTools.jl has had 306 committs, and one of the issues it has is "@btime in local scope throws UndefVarError". This error is occuring when BenchmarkTools won't allow @btime to be used for some pieces of code without saying that values are undefined. This issue may be avoided by "interpolating" external variables.

According to the Repo, @btime is useful for smaller checks, @btime also runs much like Julia's inbuilt @time function, giving the minimum time elapsed for the code to run, whereas @benchmark is designed to give the common/base of the code. When using @benchmark, external values need to be interpolated, additionally @benchmark is useful for bigger macro checks.

In [ ]:
using BenchmarkTools

function find_special_plate(indexes, plates; special_index = 1234567890)
    for (i, index) in enumerate(indexes) 
        if index == special_index 
            return plates[i]
        end
    end 
    throw(Error("Index not found"))
end

indexes, plates = prepare_sorted_data()

@benchmark find_special_plate(indexes, plates)

#### 7c:

#### 7d:

# Solution to [Question 8](https://courses.smp.uq.edu.au/MATH2504/2022/assessment_html/bighw.html#q8)

#### 8a:

In [3]:
function array_table(array, heading)
    println(heading,":")
    for (i,a) in enumerate(array)
        println(i,"\t",a)
    end
end

names = [   "Amy Chan",
            "Maithili Mehta",
            "Anna Foeglein",
            "Andy Ferris",
            "Thomas Graham",
            "Elaine Schenk",
            "Jesse Woods",
            "Tina Moghaddam",
            "Paul Bellette",
            "Paul Vrbik",
            "Tom Cranitch",
            "Yoni Nazarathy",
            "Sam Hambleton",
            "Alistair Falconer",
            "Emma Comino",
            "Ivana Carrizo-Molina"]


sorted_names = sort(names,by=length)
array_table(sorted_names,"Sorted by shortest last name")

Sorted by shortest last name:
1	Amy Chan
2	Paul Vrbik
3	Andy Ferris
4	Jesse Woods
5	Emma Comino
6	Tom Cranitch
7	Anna Foeglein
8	Thomas Graham
9	Elaine Schenk
10	Paul Bellette
11	Sam Hambleton
12	Maithili Mehta
13	Tina Moghaddam
14	Yoni Nazarathy
15	Alistair Falconer
16	Ivana Carrizo-Molina


#### 8b:

#### 8c:

#### 8d:

# Solution to [Question 9](https://courses.smp.uq.edu.au/MATH2504/2022/assessment_html/bighw.html#q9)

In [4]:
using LinearAlgebra, Random
Random.seed!(0)
A = round.(10*rand(2,3))
B = round.(10*rand(3,4))
A*B

2×4 Matrix{Float64}:
 146.0  99.0  80.0  173.0
  21.0  16.0  11.0   26.0

#### 9a:

In [5]:
function my_mult_by_cols(A, B)
    nA, mA = size(A)
    nB, mB = size(B)
    @assert mA == nB
    n, m, p = nA, mA, mB
    C = Array{Float64}(undef, n, p)
    
    for i in 1:p
        C[:, i] = sum(B[j, i] * A[:, j] for j in 1:m)
    end
    return C
end

my_mult_by_cols(A, B)

2×4 Matrix{Float64}:
 146.0  99.0  80.0  173.0
  21.0  16.0  11.0   26.0

#### 9b:

In [6]:
function my_mult_by_rows(A, B)
    nA, mA = size(A)
    nB, mB = size(B)
    @assert mA == nB
    n, m, p = nA, mA, mB
    C = Array{Float64}(undef, n, p)
    
    for i in 1:n
        C[i, :] = sum(A[i, j] * B[j, :] for j in 1:m)
    end
    return C
end

my_mult_by_rows(A, B)

2×4 Matrix{Float64}:
 146.0  99.0  80.0  173.0
  21.0  16.0  11.0   26.0

#### 9c:

In [7]:
function my_mult_sum_outer_products(A, B)
    nA, mA = size(A)
    nB, mB = size(B)
    @assert mA == nB
    n, m, p = nA, mA, mB
    C = Array{Float64}(undef, n, p)
    
    for j in 1:m
        C += A[:, j] * B[j, :]'
    end
    return C
end

my_mult_sum_outer_products(A, B)

2×4 Matrix{Float64}:
 146.0  99.0  80.0  173.0
  21.0  16.0  11.0  NaN

#### 9d:


No, 9a-c are not necessarily more efficient just because they don't have nested loops. This is because each iteration of 9a-c's singular `for` loop consists of more operations than each iteration in `my_mult_inner_product()`'s inner `for` loop. Since these `for` loops do not run the same number of operations, we can't compare them directly.

For example, in 9a, each iteration of the `for` loop calculates an entire column of `C`, whereas in `my_mult_inner_product()`, each iteration of the inner `for` loop calculates only one element of `C`. The `for` loops in 9a-c are thus roughly equivalent (in number of operations) to the outer `for` loop in `my_mult_inner_product()`, so the functions in 9a-c are not necessarily more efficient.